### ISSUE TITLE
DATABASE FİLE ?   ФАЙЛ БАЗЫ ДАННЫХ?

### ISSUE THREAD

**Issue by pepekayu** [Stamir36/Cursus#1]
hello, why is the database file missing? I couldn't see the .sql file in the files.

привет, почему файл базы данных отсутствует? Я не мог видеть файл .sql в файлах.

**Comment by Stamir36** [comment]
Answer provided via chat: https://t.me/unesell
----
Ответ предоставлен в чате: https://t.me/unesell
